server:
  port: 18100
  servlet:
    context-path: /cardbank

spring:
  application:
    name: cardbank

  datasource:
    url: jdbc:mysql://localhost:3306/cardbank?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
