server:
  port: 8765

spring:
  application:
    name: gateway
  jwt:
    secret: princessSecretKey
    token:
      access-expiration-time: 86400000     # 24시간
      refresh-expiration-time: 604800000   # 7일
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT
          predicates:
            - Path=/moapay/pay/**
        - id: cardbank-service
          uri: lb://cardbank
          predicates:
            - Path=/cardbank/**
        # 필터 검증하지 않는 member-service
        - id: member-service
          uri: lb://member
          predicates:
            - Path=/moapay/member/login, /moapay/member/join, /moapay/member/sendSMS, /moapay/member/verification, /moapay/member/isMember
          filters:
            - RewritePath=/moapay/member/(?<segment>.*),/$\{segment}
        # 필터 검증 필요한 member-service
        - id: member-service
          uri: lb://member
          predicates:
            - Path=/moapay/member/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/moapay/member/(?<segment>.*),/$\{segment}
        - id: moapay-service
          uri: lb://moapay
          predicates:
            - Path=/moapay/core/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
