server:
  port: 8765

spring:
  application:
    name: gateway
  jwt:
    secret: princessSecretKeyverylonghappyprojectmoapayiwanttogohomeohmygodhowlong
    token:
      access-expiration-time: 86400000     # 24시간
      refresh-expiration-time: 604800000   # 7일
  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment
          predicates:
            - Path=/api/moapay/pay/**
        - id: cardbank-service
          uri: lb://cardbank
          predicates:
            - Path=/api/cardbank/**
        - id: member-service
          uri: lb://member
          predicates:
            - Path=/api/moapay/member/**
        - id: moapay-service
          uri: lb://moapay
          predicates:
            - Path=/api/moapay/core/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
