server:
  port: 8765

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
      - id: payment-service
        uri: lb://PAYMENT
        predicates:
        - Path=/payment/pay/**


