server:
  port: 8765

spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: princessSecretKeyverylonghappyprojectmoapayiwanttogohomeohmygodhowlong
    token:
      access-expiration-time: 86400000     # 24시간
      refresh-expiration-time: 604800000   # 7일
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: payment-service
          uri: lb://PAYMENT
          predicates:
            - Path=/moapay/pay/**
        - id: member-service
          uri: lb://member
          predicates:
            - Path=/moapay/member/**
        - id: moapay-service
          uri: lb://moapay
          predicates:
            - Path=/moapay/core/**
        - id: dutchpay-service
          uri: lb:ws://DUTCHPAY-SERVICE
          predicates:
            - Path=/moapay/core/ws/dutchpay
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/moapay/core/ws/dutchpay, /ws/dutchpay

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
