server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT
          predicates:
            - Path=/payment/pay/**
        - id: cardbank-service
          uri: lb://cardbank
          predicates:
            - Path=/cardbank/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


