server:
  port: 18040

spring:
  application:
    name: member
  redis:
    host: localhost
    port: 6379
    password: moaprincess
  jwt:
    secret: princessSecretKeyverylonghappyprojectmoapayiwanttogohomeohmygodhowlong
    token:
      access-expiration-time: 86400000 # 24시간
      refresh-expiration-time: 604800000 # 7일
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
