server:
  servlet:
    context-path: /api

spring:
  application:
    name: member
  redis:
    host: member-redis
    port: 6379
    password: moaprincess
  jwt:
    secret: princessSecretKeyverylonghappyprojectmoapayiwanttogohomeohmygodhowlong
    token:
      access-expiration-time: 864000001 #  24 * 10시간
      refresh-expiration-time: 604800000 # 7일
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://member-mysql:3306/member?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      uri: http://config-server:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG
