server:
  port: 18040

spring:
  application:
    name: member

  datasource:
    url: jdbc:mysql://member-mysql:3306/member?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
