server:
  servlet:
    context-path: /api/moapay/core

spring:
  application:
    name: moapay

  datasource:
    url: jdbc:mysql://moapay-mysql:3306/moapay?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: moapay-redis
    port: 6379
    qrcode-expire: 5
    barcode-expire: 5

  cloud:
    config:
      uri: http://config-server:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
