server:
  servlet:
    context-path: /api/moapay/core

spring:
  application:
    name: moapay

  kafka:
    bootstrap-servers:
      - kafka-00:19092
      - kafka-01:19093
      - kafka-02:19094
    consumer:
      group-id: payments_consumer_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max-poll-records: 500
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      enable-idempotence: true
      batch-size: 1

  datasource:
    url: jdbc:mysql://moapay-mysql:3306/moapay?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host: moapay-redis
    port: 6379
    password: moaprincess
    qrcode-expire: 5
    barcode-expire: 5

  cloud:
    config:
      uri: http://config-server:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"

fcm:
  MoaPayFCM: MoaPayFCM.json

external-url:
  cardbank: https://j11c201.p.ssafy.io/cardapi/cardbank
  store: https://j11c201.p.ssafy.io/storeapi/store
  payment: https://j11c201.p.ssafy.io/api/moapay/pay
