server:
  port: 18020

spring:
  application:
    name: moapay

  kafka:
    bootstrap-servers: 
      - localhost:9092
      - localhost:9092
      - localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/moapay?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
