server:
  servlet:
    context-path: /api/moapay/pay

spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://payment-mysql:3306/payment?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  redis:
    host: payment-redis
    port: 6379
    password: moaprincess
    qrcode-expire: 5
  kafka:
    consumer:
      auto-offset-reset: earliest

  cloud:
    config:
      uri: http://config-server:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"

external-url:
  moapay: https://j11c201.p.ssafy.io/api/moapay
  core: https://j11c201.p.ssafy.io/api/moapay/core
  member: https://j11c201.p.ssafy.io/api/moapay/member