server:
  port: 18010
  servlet:
    context-path: /moapay/pay
    

spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: princess
    password: moaprincess

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    qrcode-expire: 5
  kafka:
    consumer:
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
